import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('🍔 Inserindo comidas no banco...');

  await prisma.comidas.deleteMany();

  await prisma.comidas.createMany({
    data: [
        { nome: "Cachorro-quente gourmet",
        tipo: "Lanche",
        preco: 9.50,
        descricao: "Salsicha artesanal com pão especial e molho caseiro." },
      { nome: "Hambúrguer vegetariano",
        tipo: "Lanche",
        preco: 11.00,
        descricao: "Hambúrguer de grão-de-bico com salada fresca." },
      { nome: "Risoto de cogumelos",
        tipo: "Prato principal",
        preco: 18.50,
        descricao: "Risoto cremoso com mix de cogumelos frescos." },
      { nome: "Filé de salmão grelhado",
        tipo: "Proteína",
        preco: 22.00,
        descricao: "Salmão grelhado com ervas finas e limão siciliano." },
      { nome: "Espaguete à bolonhesa",
        tipo: "Prato principal",
        preco: 16.00,
        descricao: "Massa italiana com molho à base de carne moída." },
      { nome: "Quiche de espinafre",
        tipo: "Prato principal",
        preco: 12.00,
        descricao: "Quiche cremosa de espinafre com queijo." },
      { nome: "Wrap de frango",
        tipo: "Lanche",
        preco: 10.50,
        descricao: "Tortilla recheada com frango, alface e molho especial." },
      { nome: "Salada Caesar",
        tipo: "Acompanhamento",
        preco: 9.00,
        descricao: "Alface, croutons e molho Caesar." },
      { nome: "Sopa de abóbora",
        tipo: "Prato principal",
        preco: 11.00,
        descricao: "Sopa cremosa de abóbora com gengibre." },
      { nome: "Tacos mexicanos",
        tipo: "Lanche",
        preco: 14.00,
        descricao: "Tortillas recheadas com carne temperada e guacamole." },
      { nome: "Peito de frango ao molho de mostarda",
        tipo: "Proteína",
        preco: 19.00,
        descricao: "Frango grelhado com molho de mostarda e mel." },
      { nome: "Linguine ao pesto",
        tipo: "Prato principal",
        preco: 17.50,
        descricao: "Massa com molho pesto de manjericão e parmesão." },
      { nome: "Carne assada com batatas",
        tipo: "Prato principal",
        preco: 20.00,
        descricao: "Carne bovina assada com batatas e temperos." },
      { nome: "Moqueca de camarão",
        tipo: "Prato principal",
        preco: 25.00,
        descricao: "Camarões cozidos com leite de coco e dendê." },
      { nome: "Bolinho de bacalhau",
        tipo: "Lanche",
        preco: 8.50,
        descricao: "Bolinho crocante de bacalhau com temperos." },
      { nome: "Panqueca de frango com catupiry",
        tipo: "Lanche",
        preco: 11.50,
        descricao: "Panqueca recheada com frango desfiado e catupiry." },
      { nome: "Torta de legumes",
        tipo: "Prato principal",
        preco: 13.00,
        descricao: "Torta salgada com legumes frescos e temperos." },
      { nome: "Arroz de pato",
        tipo: "Prato principal",
        preco: 22.00,
        descricao: "Arroz com pato desfiado e temperos especiais." },
      { nome: "Peixe ao molho de ervas",
        tipo: "Proteína",
        preco: 20.50,
        descricao: "Filé de peixe grelhado com molho de ervas finas." },
      { nome: "Camarão na moranga",
        tipo: "Prato principal",
        preco: 28.00,
        descricao: "Camarões servidos dentro da moranga com creme." },
      { nome: "Salada de quinoa",
        tipo: "Acompanhamento",
        preco: 10.00,
        descricao: "Quinoa, legumes e molho de limão siciliano." },
      { nome: "Espetinho de carne",
        tipo: "Proteína",
        preco: 12.00,
        descricao: "Espetinho grelhado com carne bovina e temperos." },
      { nome: "Falafel",
        tipo: "Lanche",
        preco: 9.00,
        descricao: "Bolinho frito de grão-de-bico e especiarias." },
      { nome: "Berinjela à parmegiana",
        tipo: "Prato principal",
        preco: 15.00,
        descricao: "Berinjela gratinada com molho de tomate e queijo." },
      { nome: "Ceviche de peixe",
        tipo: "Prato principal",
        preco: 18.50,
        descricao: "Peixe fresco marinado em limão com cebola e coentro." },
      { nome: "Panqueca de ricota e espinafre",
        tipo: "Lanche",
        preco: 10.00,
        descricao: "Panqueca recheada com ricota e espinafre." },
      { nome: "Omelete de queijo",
        tipo: "Café da manhã",
        preco: 6.50,
        descricao: "Omelete simples com queijo derretido." },
      { nome: "Crepe de Nutella",
        tipo: "Lanche",
        preco: 8.00,
        descricao: "Crepe doce recheado com Nutella." },
      { nome: "Pizza calabresa",
        tipo: "Prato principal",
        preco: 14.00,
        descricao: "Pizza tradicional com calabresa e queijo." },
      { nome: "Pizza portuguesa",
        tipo: "Prato principal",
        preco: 15.00,
        descricao: "Pizza com presunto, ovo, cebola e azeitonas." },
      { nome: "Risoto de frango com cogumelos",
        tipo: "Prato principal",
        preco: 19.00,
        descricao: "Risoto cremoso com frango e cogumelos." },
      { nome: "Frango à parmegiana",
        tipo: "Proteína",
        preco: 20.00,
        descricao: "Frango empanado coberto com molho de tomate e queijo." },
      { nome: "Batata rústica",
        tipo: "Acompanhamento",
        preco: 7.50,
        descricao: "Batatas assadas com temperos variados." },
      { nome: "Salada grega",
        tipo: "Acompanhamento",
        preco: 10.00,
        descricao: "Tomate, pepino, cebola, azeitonas e queijo feta." },
      { nome: "Espetinho de frango",
        tipo: "Proteína",
        preco: 11.00,
        descricao: "Espetinho grelhado de frango temperado." },
      { nome: "Crepe de queijo e presunto",
        tipo: "Lanche",
        preco: 9.50,
        descricao: "Crepe recheado com queijo e presunto." },
      { nome: "Sushi sushi",
        tipo: "Prato principal",
        preco: 22.00,
        descricao: "Combinado de sushi fresco com salmão e atum." },
      { nome: "Temaki de salmão",
        tipo: "Prato principal",
        preco: 18.00,
        descricao: "Cone de alga recheado com arroz e salmão." },
      { nome: "Yakissoba vegetariano",
        tipo: "Prato principal",
        preco: 16.50,
        descricao: "Macarrão oriental com legumes e molho especial." },
      { nome: "Espetinho misto",
        tipo: "Proteína",
        preco: 13.50,
        descricao: "Espetinho com frango, carne e linguiça." },
      { nome: "Mousse de chocolate",
        tipo: "Sobremesa",
        preco: 6.50,
        descricao: "Mousse cremosa de chocolate." },
      { nome: "Pudim de chocolate",
        tipo: "Sobremesa",
        preco: 7.00,
        descricao: "Pudim de chocolate com calda." },
      { nome: "Brownie de chocolate",
        tipo: "Sobremesa",
        preco: 5.50,
        descricao: "Brownie de chocolate com nozes." },
      { nome: "Sorvete de morango",
        tipo: "Sobremesa",
        preco: 6.50,
        descricao: "Sorvete cremoso de morango." },
      { nome: "Milkshake de chocolate",
        tipo: "Bebida",
        preco: 8.00,
        descricao: "Milkshake gelado de chocolate com chantilly." },
      { nome: "Suco de abacaxi",
        tipo: "Bebida",
        preco: 5.50,
        descricao: "Suco natural de abacaxi fresco." },
      { nome: "Chá gelado",
        tipo: "Bebida",
        preco: 4.50,
        descricao: "Chá gelado refrescante com limão." },
      { nome: "Café com leite",
        tipo: "Bebida",
        preco: 4.00,
        descricao: "Café quente com leite." },
      { nome: "Bolo de chocolate",
        tipo: "Sobremesa",
        preco: 6.50,
        descricao: "Bolo fofinho de chocolate com cobertura." },
      { nome: "Pão de mel",
        tipo: "Sobremesa",
        preco: 5.00,
        descricao: "Pão de mel recheado com doce de leite." },
      { nome: "Cheesecake de frutas vermelhas",
        tipo: "Sobremesa",
        preco: 10.00,
        descricao: "Cheesecake com calda de frutas vermelhas." },
      { nome: "Bruschetta de tomate",
        tipo: "Lanche",
        preco: 8.00,
        descricao: "Pão tostado com tomate, manjericão e azeite." },
      { nome: "Caprese salad",
        tipo: "Acompanhamento",
        preco: 9.50,
        descricao: "Salada com tomate, mussarela e manjericão fresco." }
    ]
  });

  console.log('✨ 50 comidas inseridas com sucesso!');
}

main()
  .then(async () => { await prisma.$disconnect() })
  .catch(async (e) => { console.error(e); await prisma.$disconnect(); process.exit(1) });
